# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: umBristol
description: The Bristol Umbraco User Group.
baseurl: ""
url: "http://umbristol.co.uk"
permalink: /:year/:month/:day/:title/

# accounts
twitter_username: umBristol
github_username: umBristol
meetup_username: umBristol
slack_signup: https://umbristolautosignup.herokuapp.com/
google_analytics: UA-122639-11

# collections
collections:
  events:
    output: true
    permalink: /:collection/:name

# Build settings
github: [metadata]
repository: umBristol/umbristol.github.com
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-gist
  - jemoji
